spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update # create, create-drop, update, validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # sql query print 시,  `?` 에서  data param 을 출력함